/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jap_MacOSXLib */

#ifndef _Included_jap_MacOSXLib
#define _Included_jap_MacOSXLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jap_MacOSXLib
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jap_MacOSXLib_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     jap_MacOSXLib
 * Method:    nativeInitDockMenu
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jap_MacOSXLib_nativeInitDockMenu
  (JNIEnv *, jclass);

/*
 * Class:     jap_MacOSXLib
 * Method:    getLibVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jap_MacOSXLib_getLibVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
