/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class gui_JAPMacOSXLib */

#ifndef _Included_gui_JAPMacOSXLib
#define _Included_gui_JAPMacOSXLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     gui_JAPMacOSXLib
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gui_JAPMacOSXLib_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     gui_JAPMacOSXLib
 * Method:    nativeInitDockMenu
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_gui_JAPMacOSXLib_nativeInitDockMenu
  (JNIEnv *, jclass);

/*
 * Class:     gui_JAPMacOSXLib
 * Method:    setMenu
 * Signature: (Ljavax/swing/JMenu;)V
 */
JNIEXPORT void JNICALL Java_gui_JAPMacOSXLib_setMenu
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
